<?php

$sampletypes = array(
  array('sampletypeid' => '0001','salesgroup' => 'default','sampletypeName' => 'Broilers Starter- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Broilers Starter- KS EAS 90:2023','ControlParameter' => '0'),
  array('sampletypeid' => '0002','salesgroup' => 'DEFAULT','sampletypeName' => 'Broilers Growers- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Broilers Growers- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0003','salesgroup' => 'DEFAULT','sampletypeName' => 'Broilers Finisher- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Broilers Finisher- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0004','salesgroup' => 'DEFAULT','sampletypeName' => 'Chick Feed- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Chick Feed- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0005','salesgroup' => 'DEFAULT','sampletypeName' => 'Duckling- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Duckling- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0006','salesgroup' => 'DEFAULT','sampletypeName' => 'Poults- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Poultry- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0007','salesgroup' => 'DEFAULT','sampletypeName' => 'Grower feed- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Growers feed- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0008','salesgroup' => 'DEFAULT','sampletypeName' => 'Layers feed- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Layers feed- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0009','salesgroup' => 'DEFAULT','sampletypeName' => 'Breeders feed- KS EAS 90:2023 Compounded poultry feeds','SalesPrice' => '0','StandardCode' => 'Breeders feed- KS EAS 90:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0010','salesgroup' => 'DEFAULT','sampletypeName' => 'Mature Beef Cattle KS EAS 458 : 2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Mature Beef Cattle KS EAS 458 : 2015','ControlParameter' => NULL),
  array('sampletypeid' => '0011','salesgroup' => 'DEFAULT','sampletypeName' => 'Goat and Sheep for Meat ProductionKS EAS 458 : 2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Goat and Sheep for Meat Production KS EAS 458 : 2015','ControlParameter' => NULL),
  array('sampletypeid' => '0012','salesgroup' => 'DEFAULT','sampletypeName' => 'Goat and Sheep for Milk Production KS EAS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Goat and Sheep for Milk Production KS EAS 458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0013','salesgroup' => 'DEFAULT','sampletypeName' => 'Growing Stock KS EAS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Growing Stock KS EAS 458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0014','salesgroup' => 'DEFAULT','sampletypeName' => 'Bulling Heifers/yearling  KS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Bulling Heifers/Yearlings  KS EAS 458:2015','ControlParameter' => NULL),
  array('sampletypeid' => '0015','salesgroup' => 'DEFAULT','sampletypeName' => 'Lactaning Beef Cows KS EAS458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Lactaning Beef Cows KS EAS458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0016','salesgroup' => 'DEFAULT','sampletypeName' => 'Dry Dairy Cows KS EAS458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Dry Dairy Cows KS EAS458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0017','salesgroup' => 'DEFAULT','sampletypeName' => 'Lactaning Dairy Cows KS EAS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Lactaning Dairy Cows KS EAS 458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0018','salesgroup' => 'DEFAULT','sampletypeName' => 'Dry Dairy Cows KS EAS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Dry Dairy Cows KS EAS 458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0019','salesgroup' => 'DEFAULT','sampletypeName' => 'Equines KS EAS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Equines KS EAS 458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0020','salesgroup' => 'DEFAULT','sampletypeName' => 'Carmels KS EAS 458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Carmels KS EAS 458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0021','salesgroup' => 'DEFAULT','sampletypeName' => 'Pig starter KS EAS 55:2019 Compounded pig feed','SalesPrice' => '0','StandardCode' => 'Pig starter KS EAS 55:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0022','salesgroup' => 'DEFAULT','sampletypeName' => 'Pig Grower KS EAS 55:2019 Compounded pig feed','SalesPrice' => '0','StandardCode' => 'Pig Grower KS EAS 55:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0023','salesgroup' => 'DEFAULT','sampletypeName' => 'Pig Finisher KS EAS 55:2019 Compounded pig feed','SalesPrice' => '0','StandardCode' => 'Pig Finisher KS EAS 55:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0024','salesgroup' => 'DEFAULT','sampletypeName' => 'Lactacting Sow KS EAS 55:2019 Compounded pig feed','SalesPrice' => '0','StandardCode' => 'Lactacting Sow KS EAS 55:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0025','salesgroup' => 'DEFAULT','sampletypeName' => 'Salt Block For General Live stock KS EAS  458 :2015 Mineral supplements','SalesPrice' => '0','StandardCode' => 'Salt Block For General Live stock KS EAS  458 :2015','ControlParameter' => NULL),
  array('sampletypeid' => '0026','salesgroup' => 'DEFAULT','sampletypeName' => 'Calf Starter feed EAS 75: 2019 Compounded Cattle Feeds','SalesPrice' => '0','StandardCode' => 'Calf Starter feed EAS 75: 2019','ControlParameter' => NULL),
  array('sampletypeid' => '0027','salesgroup' => 'DEFAULT','sampletypeName' => 'Calf  feed EAS 75: 2019 Compounded Cattle Feeds','SalesPrice' => '0','StandardCode' => 'Calf  feed EAS 75: 2019','ControlParameter' => NULL),
  array('sampletypeid' => '0028','salesgroup' => 'DEFAULT','sampletypeName' => 'Weaner  feed EAS 75: 2019 Compounded Cattle Feeds','SalesPrice' => '0','StandardCode' => 'Weaner feed EAS 75: 2019','ControlParameter' => NULL),
  array('sampletypeid' => '0029','salesgroup' => 'DEFAULT','sampletypeName' => 'Dairy Cattle  feed EAS 75: 2019 Compounded Cattle Feeds','SalesPrice' => '0','StandardCode' => 'Dairy Cattle  feed EAS 75: 2019','ControlParameter' => NULL),
  array('sampletypeid' => '0030','salesgroup' => 'DEFAULT','sampletypeName' => 'Beef Cattle  feed EAS 75: 2019 Compounded Cattle Feeds','SalesPrice' => '0','StandardCode' => 'Beef Cattle  feed EAS 75: 2019','ControlParameter' => NULL),
  array('sampletypeid' => '0031','salesgroup' => 'DEFAULT','sampletypeName' => 'Draught Cattle  feed EAS 75: 2019 Compounded Cattle Feeds','SalesPrice' => '0','StandardCode' => 'Draught Cattle feed EAS 75: 2019','ControlParameter' => NULL),
  array('sampletypeid' => '0032','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 142:2000 Vodka Specification','SalesPrice' => '0','StandardCode' => 'Vodka Specification EAS 142 :2000','ControlParameter' => NULL),
  array('sampletypeid' => '0033','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 142:2000 Vodka Specification','SalesPrice' => '0','StandardCode' => 'Vodka Specification EAS 142 :2010','ControlParameter' => NULL),
  array('sampletypeid' => '0034','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 142:2000 Vodka Specification','SalesPrice' => '0','StandardCode' => 'Vodka Specification EAS 142 :2000','ControlParameter' => NULL),
  array('sampletypeid' => '0035','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 145 :2014 Gin Specification','SalesPrice' => '0','StandardCode' => 'Gin Specification EAS 145 :2014','ControlParameter' => NULL),
  array('sampletypeid' => '0036','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 2 :2011   Grade 1 Maize grains Specification','SalesPrice' => '0','StandardCode' => 'Grade 1 Maize Grains Specifications EAS 2 :2011','ControlParameter' => NULL),
  array('sampletypeid' => '0037','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 2 :2011   Grade 2 Maize grains Specification','SalesPrice' => '0','StandardCode' => 'Grade 2 Maize Grains Specifications EAS 2 :2011','ControlParameter' => NULL),
  array('sampletypeid' => '0038','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 2 :2011   Grade 3 Maize grains Specification','SalesPrice' => '0','StandardCode' => 'Grade 3 Maize Grains Specifications EAS 2 :2011','ControlParameter' => NULL),
  array('sampletypeid' => '0039','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 749 - Light Brown Sugar Specifications','SalesPrice' => '0','StandardCode' => 'Light Brown Sugar Specifications EAS 746:2010','ControlParameter' => NULL),
  array('sampletypeid' => '0040','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 749 - Brown Sugar Specifications','SalesPrice' => '0','StandardCode' => 'Brown Sugar Specifications EAS 746:2010','ControlParameter' => NULL),
  array('sampletypeid' => '0041','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 740 - Cassava Flour Specification','SalesPrice' => '0','StandardCode' => 'Cassava Flour Specification EAS 740 : 2010','ControlParameter' => NULL),
  array('sampletypeid' => '0042','salesgroup' => 'DEFAULT','sampletypeName' => 'Environmental management & coordination (Water Quality) regulations 2006, Legal Notice No. 120,3rd Schedule guidelines','SalesPrice' => '0','StandardCode' => 'EMCA 3rd Schedule','ControlParameter' => NULL),
  array('sampletypeid' => '0043','salesgroup' => 'DEFAULT','sampletypeName' => 'Environmental Management &Coordination (Water Quality) Regulations 2006, Legal Notice No. 120, 5th Schedule Guideline,','SalesPrice' => '0','StandardCode' => 'EMCA 5th Schedule','ControlParameter' => NULL),
  array('sampletypeid' => '0044','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 12 2018 Kenya potable water specifications - Natural','SalesPrice' => '0','StandardCode' => 'KS 12 2018- Natural','ControlParameter' => NULL),
  array('sampletypeid' => '0045','salesgroup' => 'default','sampletypeName' => 'KS 12 2018 Kenya potable water specifications - Treated','SalesPrice' => '0','StandardCode' => 'KS 12 2018- Treated','ControlParameter' => '0'),
  array('sampletypeid' => '0047','salesgroup' => 'DEFAULT','sampletypeName' => 'Environmental Management &Coordination (Water Quality) Regulations 2006, Legal Notice No. 120, Sources of Domestic Water','SalesPrice' => '0','StandardCode' => 'EMCA 1st Schedule','ControlParameter' => NULL),
  array('sampletypeid' => '0048','salesgroup' => 'default','sampletypeName' => 'KS EAS 812 - 2023 Synthetic  Liquid Hand Wash Specification','SalesPrice' => '0','StandardCode' => 'Synthetic Liquid Hand wash specification EAS 812 :2023','ControlParameter' => '0'),
  array('sampletypeid' => '0049','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 812 : 2022 Combined (Synthetic and soap)Liquid Hand wash specification','SalesPrice' => '0','StandardCode' => 'Combined (Synthetic and soap)Liquid Hand wash specification KS EAS 812 :2022','ControlParameter' => NULL),
  array('sampletypeid' => '0050','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 835-1:2021  Bath Preparations','SalesPrice' => '0','StandardCode' => 'Bath Preparations specifications KSEAS 835-1 : 2021','ControlParameter' => NULL),
  array('sampletypeid' => '0051','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 792 :2021 Carpet and Upholstery Shampoo','SalesPrice' => '0','StandardCode' => 'Carpet and Upholstery Shampoo KS EAS 792 : 2021','ControlParameter' => NULL),
  array('sampletypeid' => '0052','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 77 : 2022 Fruit Drinks Specifications','SalesPrice' => '0','StandardCode' => 'Fruit Drinks Specifications KS EAS 77 : 2022','ControlParameter' => NULL),
  array('sampletypeid' => '0053','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 383:2020 Liquid Detergent For Household Use- General Purpose','SalesPrice' => '0','StandardCode' => 'Liquid Detergent For Household Use- General Purpose-EAS 383:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0054','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 383:2020  Liquid Detergent For Household Use- DishWashing','SalesPrice' => '0','StandardCode' => 'Liquid Detergent For Household Use- DishWashing-EAS 383:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0055','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 842-1:2021Synthetic detergent Hair Shampoo-General Purpose','SalesPrice' => '0','StandardCode' => 'Synthetic detergent Hair Shampoo-General Purpose : EAS 842-1 :2021','ControlParameter' => NULL),
  array('sampletypeid' => '0056','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 842-1:2021Synthetic detergent Hair Shampoo-General Purpose','SalesPrice' => '0','StandardCode' => 'Synthetic detergent Hair Shampoo-General Purpose EAS 842-1 :2021','ControlParameter' => NULL),
  array('sampletypeid' => '0057','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 842-1 :2021 Synthetic detergent Hair Shampoo -Baby','SalesPrice' => '0','StandardCode' => 'Synthetic detergent Hair Shampoo -Baby  EAS 842-1 :2021','ControlParameter' => NULL),
  array('sampletypeid' => '0058','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 842-1 :2021 Synthetic detergent Hair Shampoo -Neutralizing','SalesPrice' => '0','StandardCode' => 'Synthetic detergent Hair Shampoo -Neutralizing EAS 842-1 :2021','ControlParameter' => NULL),
  array('sampletypeid' => '0059','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 842-1 :2021 Synthetic detergent Hair Shampoo -Multifunctional','SalesPrice' => '0','StandardCode' => 'Synthetic detergent Hair Shampoo -Multifunctional 842-1 :2021','ControlParameter' => NULL),
  array('sampletypeid' => '0061','salesgroup' => 'DEFAULT','sampletypeName' => 'Kienyenji starter Diets- KS EAS 2957:2021 Compounded Kienyenji Feeds','SalesPrice' => '0','StandardCode' => 'Kienyenji starter Diets- KS EAS 2957:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0062','salesgroup' => 'DEFAULT','sampletypeName' => 'Kienyenji Grower Diets- KS EAS 2957:2021 Compounded Kienyenji Feeds','SalesPrice' => '0','StandardCode' => 'Kienyenji Grower Diets- KS EAS 2957:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0063','salesgroup' => 'DEFAULT','sampletypeName' => 'Kienyenji Finisher Diets- KS EAS 2957:2021 Compounded Kienyenji Feeds','SalesPrice' => '0','StandardCode' => 'Kienyenji Finisher Diets- KS EAS 2957:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0099','salesgroup' => 'DEFAULT','sampletypeName' => 'Kienyenji Layer Diets- KS EAS 2957:2021 Compounded Kienyenji Feeds','SalesPrice' => '0','StandardCode' => 'Kienyenji Layer Diets- KS EAS 2957:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0100','salesgroup' => 'DEFAULT','sampletypeName' => 'Coconut (Copra) Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Coconut (Copra)Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0101','salesgroup' => 'DEFAULT','sampletypeName' => 'Ground Nut  Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Ground nut  CakeKS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0102','salesgroup' => 'DEFAULT','sampletypeName' => 'Soya Bean Cake  KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Soya Bean Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0103','salesgroup' => 'DEFAULT','sampletypeName' => 'Soya Bean Meal  KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Soya Bean Meal  KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0104','salesgroup' => 'DEFAULT','sampletypeName' => 'Soya Bean Full Fat KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Soya Bean Full Fat  KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0105','salesgroup' => 'DEFAULT','sampletypeName' => 'Cotton seed decorticated Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Cotton seed decorticatedCake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0106','salesgroup' => 'DEFAULT','sampletypeName' => 'Cotton seed decorticated Meal KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Cotton seed decorticated Meal KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0107','salesgroup' => 'DEFAULT','sampletypeName' => 'Cotton seed undecorticated Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Cotton seed undecorticatedCake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0108','salesgroup' => 'DEFAULT','sampletypeName' => 'Sunflower decorticated Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Sunflower decorticated Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0109','salesgroup' => 'DEFAULT','sampletypeName' => 'Sunflower decorticated Meal KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Sunflower decorticated Meal KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0110','salesgroup' => 'DEFAULT','sampletypeName' => 'Sunflower undecorticated Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Sunflower undecorticated Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0111','salesgroup' => 'DEFAULT','sampletypeName' => 'Sesame Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Sesame Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0112','salesgroup' => 'DEFAULT','sampletypeName' => 'Rape seed Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Rape seed Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0113','salesgroup' => 'DEFAULT','sampletypeName' => 'Rape seed Meal KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Rape seed Meal KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0114','salesgroup' => 'DEFAULT','sampletypeName' => 'Maize GermCake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Maize GermCake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0115','salesgroup' => 'DEFAULT','sampletypeName' => 'Amaranth Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Amaranth Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0116','salesgroup' => 'DEFAULT','sampletypeName' => 'Black seed Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Black seed Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0117','salesgroup' => 'DEFAULT','sampletypeName' => 'Chia seed Cake KS EAS 287:2019 Oilseed cakes and meal for animal','SalesPrice' => '0','StandardCode' => 'Chia seed Cake KS EAS 287:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0118','salesgroup' => 'DEFAULT','sampletypeName' => 'EAS 1797:2014  Household fabric softeners','SalesPrice' => '0','StandardCode' => 'Household fabric softeners KS EAS 1797 :2014','ControlParameter' => NULL),
  array('sampletypeid' => '0119','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 523-2:2015 Breakfast cereals Specification-Muesli','SalesPrice' => '0','StandardCode' => 'Muesli KS 523-2:2015','ControlParameter' => NULL),
  array('sampletypeid' => '0120','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 523-2:2015 Breakfast cereals Specification-Others(flaked/puffed)','SalesPrice' => '0','StandardCode' => 'flaked/puffed KS 523-2:2015','ControlParameter' => NULL),
  array('sampletypeid' => '0121','salesgroup' => 'default','sampletypeName' => 'KS EAS 69:2023 Pasteurized Milk Specifications (whole/cream milk)','SalesPrice' => '0','StandardCode' => 'Whole/cream milk KS EAS 69:2023','ControlParameter' => '0'),
  array('sampletypeid' => '0122','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 69:2023 Pasteurized Milk Specifications (Semi-skimmed/reduced fat)','SalesPrice' => '0','StandardCode' => 'Semi-skimmed/reduced fat  KS EAS 69:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0123','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 69:2023 Pasteurized Milk Specifications (Low fat Milk)','SalesPrice' => '0','StandardCode' => 'Low fat Milk KS EAS 69:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0124','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 69:2023 Pasteurized Milk Specifications (Fat free/skimmed Milk)','SalesPrice' => '0','StandardCode' => 'Fat free/skimmed Milk KS EAS 69:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0125','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1024: 2021 Fortified Composite flour Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 1024: 2021','ControlParameter' => NULL),
  array('sampletypeid' => '0126','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 993:2020  Baking powder Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 993','ControlParameter' => NULL),
  array('sampletypeid' => '0127','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 781:2012 Biscuits Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 781','ControlParameter' => NULL),
  array('sampletypeid' => '0128','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 58-1:2021 Compounded dog food-Puppy Specifications','SalesPrice' => '0','StandardCode' => 'Puppy KS EAS 58-1','ControlParameter' => NULL),
  array('sampletypeid' => '0129','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 58-1:2021 Compounded Adult dog food Specifications','SalesPrice' => '0','StandardCode' => 'Adult Dog KS EAS 58-1','ControlParameter' => NULL),
  array('sampletypeid' => '0130','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 58-1:2021 Compounded Lactating dog food Specifications','SalesPrice' => '0','StandardCode' => 'Lactating Dog KS EAS 58-1','ControlParameter' => NULL),
  array('sampletypeid' => '0131','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Ice Cream','SalesPrice' => '0','StandardCode' => 'Ice Cream KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0132','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Soft serve Mix','SalesPrice' => '0','StandardCode' => 'Soft serve Mix KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0133','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Gelato','SalesPrice' => '0','StandardCode' => 'Gelato KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0134','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Ice Milk','SalesPrice' => '0','StandardCode' => 'Ice Milk KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0135','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Frozen Yoghurt','SalesPrice' => '0','StandardCode' => 'Frozen Yoghurt KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0136','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Frozen custard','SalesPrice' => '0','StandardCode' => 'Frozen custard KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0137','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Sherbet','SalesPrice' => '0','StandardCode' => 'Sherbet KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0138','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Milk Shake','SalesPrice' => '0','StandardCode' => 'Milk Shake KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0139','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1517:2022 Dairy-Based Desserts Specifications for Frozen dairy dessert/novelties/confections','SalesPrice' => '0','StandardCode' => 'Frozen dairy dessert KS 1517:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0140','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 661:2007 Cookies Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 661','ControlParameter' => NULL),
  array('sampletypeid' => '0141','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1000: 2021 Raw Cashew Nuts Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 1000','ControlParameter' => NULL),
  array('sampletypeid' => '0142','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1004: 2021 Raw Macadamia Kernel Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 1004: 2021','ControlParameter' => NULL),
  array('sampletypeid' => '0143','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 33:2019 Yoghurt Specifications Whole Yoghurt','SalesPrice' => '0','StandardCode' => 'Whole Yoghurt KS EAS 33','ControlParameter' => NULL),
  array('sampletypeid' => '0144','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 33:2019 Yoghurt Specifications Low Fat Yoghurt','SalesPrice' => '0','StandardCode' => 'Low Fat Yoghurt KS EAS 33','ControlParameter' => NULL),
  array('sampletypeid' => '0145','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 33:2019 Yoghurt Specifications Skimmed Yoghurt','SalesPrice' => '0','StandardCode' => 'Skimmed Yoghurt KS EAS 33','ControlParameter' => NULL),
  array('sampletypeid' => '0146','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 33:2019 Yoghurt Specifications High Fat Yoghurt','SalesPrice' => '0','StandardCode' => 'High Fat Yoghurt KS EAS 33','ControlParameter' => NULL),
  array('sampletypeid' => '0147','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 33:2019 Yoghurt Specifications High Fat Yoghurt','SalesPrice' => '0','StandardCode' => 'High Fat Yoghurt KS EAS 33','ControlParameter' => NULL),
  array('sampletypeid' => '0148','salesgroup' => 'default','sampletypeName' => 'KS 618:2021 Cider and Perry Specification','SalesPrice' => '0','StandardCode' => 'KS 618:2021','ControlParameter' => '0'),
  array('sampletypeid' => '0149','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 46:2017 Dry beans Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 46:2017','ControlParameter' => NULL),
  array('sampletypeid' => '0150','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 70:2023 Dairy ice creams- specification','SalesPrice' => '0','StandardCode' => 'KS EAS 70:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0151','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 828:2016 Dried and salted dried fish Specifications (Dried fish)','SalesPrice' => '0','StandardCode' => 'Dried fish KS EAS 828:2016','ControlParameter' => NULL),
  array('sampletypeid' => '0152','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 828:2016 Dried and salted dried fish Specifications (Dried salted fish)','SalesPrice' => '0','StandardCode' => 'Dried salted fish KS EAS 828:2016','ControlParameter' => NULL),
  array('sampletypeid' => '0153','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 65:2017 Specification of Coconut Oil Cosmetic','SalesPrice' => '0','StandardCode' => 'KS EAS 65:2017','ControlParameter' => NULL),
  array('sampletypeid' => '0154','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 769:2019 Fortified edible oils and fats Specification (Refined fats % oils)','SalesPrice' => '0','StandardCode' => 'Refined fats % oils KS EAS 769:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0155','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1485:2020 Fruit (Water-based) flavoured drinks Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 1485:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0156','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2150: 2022 Spirit-based Read to Drink Alcoholic','SalesPrice' => '0','StandardCode' => 'KS 2150: 2022','ControlParameter' => NULL),
  array('sampletypeid' => '0157','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2254:2004 Clove, whole and ground (powdered) Specification Whole Cloves','SalesPrice' => '0','StandardCode' => 'Whole clove KS 2254:2004','ControlParameter' => NULL),
  array('sampletypeid' => '0158','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2254:2004 Clove, whole and ground (powdered) Specification Ground Cloves','SalesPrice' => '0','StandardCode' => 'Ground/Powdered clove KS 2254:2004','ControlParameter' => NULL),
  array('sampletypeid' => '0159','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2325-1:2021 Rabbit feed - Specification Part 1: Complete Food Grower/Finisher','SalesPrice' => '0','StandardCode' => 'Grower/Finisher feed KS 2325-1:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0160','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2325-1:2021 Rabbit feed - Specification Part 1: Complete Food Female feed','SalesPrice' => '0','StandardCode' => 'Female rabbit feed KS 2325-1:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0161','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2325-1:2021 Rabbit feed - Specification Part 1: Complete Food Weaner/pregrower','SalesPrice' => '0','StandardCode' => 'Weaner/pregrower rabbit feed KS 2325-1:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0162','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2839-5:2023 Blended flour -Specification Part 5: Wheat and sorghum blend','SalesPrice' => '0','StandardCode' => 'KS 2839-5:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0163','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 331:2019 Green grams-Specification grade 1','SalesPrice' => '0','StandardCode' => 'Grade 1 KS EAS 331:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0164','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 331:2019 Green grams-Specification grade 2','SalesPrice' => '0','StandardCode' => 'Grade 2 KS EAS 331:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0165','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 331:2019 Green grams-Specification grade 3','SalesPrice' => '0','StandardCode' => 'Grade 3 KS EAS 331:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0166','salesgroup' => 'default','sampletypeName' => 'KS EAS 35:2021 Fortified edible Salt Specifications Table Salt','SalesPrice' => '0','StandardCode' => 'Table Salt KS EAS 35:2021','ControlParameter' => '0'),
  array('sampletypeid' => '0167','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 35:2021 Fortified edible Salt Specifications Coarse/Crushed Salt','SalesPrice' => '0','StandardCode' => 'Coarse/Crushed Salt KS EAS 35:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0168','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 36:2020 Honey Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 36:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0169','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 84-1:2020 Meat grades and meat cuts: Beef grades and cuts, veal grades','SalesPrice' => '0','StandardCode' => 'Beef grades, cuts, veal grades KS EAS 84-1:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0170','salesgroup' => 'default','sampletypeName' => 'KS EAS 84-2:2020 Meat grades and meat cuts: Ovine','SalesPrice' => '0','StandardCode' => 'Ovine KS EAS 84-2:2022','ControlParameter' => '0'),
  array('sampletypeid' => '0171','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 84-1:2020 Meat grades and meat cuts: Ovine','SalesPrice' => '0','StandardCode' => 'KS EAS 84-1:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0172','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 84-3:2022 Meat grades and meat cuts Specification: Pork','SalesPrice' => '0','StandardCode' => 'KS EAS 84-3:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0173','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 1756:2021 Flavoured Milk Specifications Whole/full cream milk','SalesPrice' => '0','StandardCode' => 'KS 1756:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0174','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 22:2019 Butter Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 22:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0175','salesgroup' => 'DEFAULT','sampletypeName' => 'KS ISO 5560:1997 Dehydrated Garlic Specifications Allium sativum L.','SalesPrice' => '0','StandardCode' => 'KS ISO 5560:1997','ControlParameter' => NULL),
  array('sampletypeid' => '0176','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1078:2022 Spices - Cumin (ground) Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1078:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0177','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1076:2022 Ground Cinnamon Specification-Sri lanklan type','SalesPrice' => '0','StandardCode' => 'KS EAS 1076:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0178','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 768:2019 Fortified milled maize (corn) products specifications Sifted maize flour','SalesPrice' => '0','StandardCode' => 'KS EAS 768:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0179','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 66-2:2017 Tomato products Specification (sauce)','SalesPrice' => '0','StandardCode' => 'KS EAS 66-2:2017','ControlParameter' => NULL),
  array('sampletypeid' => '0180','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 5559-1995 Dehydrated Onions','SalesPrice' => '0','StandardCode' => 'KS 5559-1995','ControlParameter' => NULL),
  array('sampletypeid' => '0181','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 838:2013 Meat and bone meal for compounding animal feeds- specification','SalesPrice' => '0','StandardCode' => 'KS 838:2013 Meat and bone meal Specification','ControlParameter' => NULL),
  array('sampletypeid' => '0182','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1008:2021 Fermented Whole milk (Cultured) milk Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1008:2021  Fermented Whole milk','ControlParameter' => NULL),
  array('sampletypeid' => '0183','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1008:2021 Reduced Fat fermented milk (Cultured) milk Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1008:2021 Reduced Fat Fermented Whole milk','ControlParameter' => NULL),
  array('sampletypeid' => '0184','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1008:2021 Fermented low fat milk (Cultured) milk Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1008:2021 Low Fat Fermented Whole milk','ControlParameter' => NULL),
  array('sampletypeid' => '0185','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1008:2021 Fermented fat free milk (Cultured) milk Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1008:2021 Fat Free  Fermented Whole milk','ControlParameter' => NULL),
  array('sampletypeid' => '0186','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1008:2021 Fermented high fat milk (Cultured) milk Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1008:2021 High Fat  Fermented Whole milk','ControlParameter' => NULL),
  array('sampletypeid' => '0187','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 16:2021 Plantation (mill) White Sugar Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 16:2021','ControlParameter' => NULL),
  array('sampletypeid' => '0188','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 26:2020 Canned corned beef - Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 26:2020','ControlParameter' => NULL),
  array('sampletypeid' => '0189','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 919:2019 Pilau masala Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 919:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0190','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 920:2019 Tea Masala specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 920:2019','ControlParameter' => NULL),
  array('sampletypeid' => '0191','salesgroup' => 'DEFAULT','sampletypeName' => 'KS ISO 20377: 2018 Dried Parsley Specification whole cut leaves','SalesPrice' => '0','StandardCode' => 'KS ISO 20377','ControlParameter' => NULL),
  array('sampletypeid' => '0192','salesgroup' => 'DEFAULT','sampletypeName' => 'KS ISO 20377: 2018 Dried Parsley Specification Rubbed (ground)','SalesPrice' => '0','StandardCode' => 'KS ISO 20377: 2018','ControlParameter' => NULL),
  array('sampletypeid' => '0193','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 916:2019 Ginger Specification Whole or pieces','SalesPrice' => '0','StandardCode' => 'KS EAS 916:2019 Ginger- Whole','ControlParameter' => NULL),
  array('sampletypeid' => '0194','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 916:2019 Ginger Specification Ground','SalesPrice' => '0','StandardCode' => 'KS EAS 916:2019 Ginger- Ground','ControlParameter' => NULL),
  array('sampletypeid' => '0195','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 2502:2013 Liquid oxygen based bleach specifications','SalesPrice' => '0','StandardCode' => 'KS 2502:2013','ControlParameter' => NULL),
  array('sampletypeid' => '0196','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1050:2022 Kitchen paper towel Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1050:2022 - Paper Towel','ControlParameter' => NULL),
  array('sampletypeid' => '0197','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1050:2022 Kitchen paper towel Specification in roll form','SalesPrice' => '0','StandardCode' => 'KS EAS 1050:2022 - Paper Roll','ControlParameter' => NULL),
  array('sampletypeid' => '0198','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 1050:2022 Kitchen paper towel Specification in sheet form','SalesPrice' => '0','StandardCode' => 'KS EAS 1050:2022 - Paper Sheet','ControlParameter' => NULL),
  array('sampletypeid' => '0199','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 861:2022 Paper serviettes (napkins) Specifications pure virgin fibre','SalesPrice' => '0','StandardCode' => 'KS EAS 861:2022 - Napkins virgin fibre','ControlParameter' => NULL),
  array('sampletypeid' => '0200','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 861:2022 Paper serviettes (napkins) Specifications Blended fibre','SalesPrice' => '0','StandardCode' => 'KS EAS 861:2022 - Napkins Blended fibre','ControlParameter' => NULL),
  array('sampletypeid' => '0201','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 861:2022 Paper serviettes (napkins) Specifications Recyled fibre','SalesPrice' => '0','StandardCode' => 'KS EAS 861:2022 - Napkins Recycled fibre','ControlParameter' => NULL),
  array('sampletypeid' => '0202','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 862:2022 Facial Tissues paper Specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 862:2022','ControlParameter' => NULL),
  array('sampletypeid' => '0203','salesgroup' => 'DEFAULT','sampletypeName' => 'KS EAS 27:2023 UHT Milk specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 27:2023','ControlParameter' => NULL),
  array('sampletypeid' => '0204','salesgroup' => 'DEFAULT','sampletypeName' => 'EMCA 8th and 9th Schedule - Irrigation Water','SalesPrice' => '0','StandardCode' => 'EMCA 8th and 9th','ControlParameter' => NULL),
  array('sampletypeid' => '0205','salesgroup' => 'DEFAULT','sampletypeName' => 'Air Quality Plates','SalesPrice' => '0','StandardCode' => 'Air Quality Plates','ControlParameter' => NULL),
  array('sampletypeid' => '0206','salesgroup' => 'DEFAULT','sampletypeName' => 'CCBA Effluent Water','SalesPrice' => '0','StandardCode' => 'CCBA Effluent Water','ControlParameter' => NULL),
  array('sampletypeid' => '0207','salesgroup' => 'DEFAULT','sampletypeName' => 'CCBA Effluent Water','SalesPrice' => '0','StandardCode' => 'CCBA Effluent Water','ControlParameter' => NULL),
  array('sampletypeid' => '0208','salesgroup' => 'DEFAULT','sampletypeName' => 'KS 809-3:2013 Neutral liquid toilet cleaners','SalesPrice' => '0','StandardCode' => 'KS 809-3:2013','ControlParameter' => NULL),
  array('sampletypeid' => '0213','salesgroup' => 'default','sampletypeName' => 'Raw Material  ','SalesPrice' => '0','StandardCode' => 'Raw Materials','ControlParameter' => '0'),
  array('sampletypeid' => '0214','salesgroup' => 'default','sampletypeName' => 'Hygiene Swabs ','SalesPrice' => '0','StandardCode' => '','ControlParameter' => '0'),
  array('sampletypeid' => '0215','salesgroup' => 'default','sampletypeName' => ' Raw cow milk - Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 67:2023','ControlParameter' => '0'),
  array('sampletypeid' => '0216','salesgroup' => 'default','sampletypeName' => 'Horizontal methods for sampling techniques from surfaces','SalesPrice' => '0','StandardCode' => 'KS ISO 18593 :2018 ','ControlParameter' => '0'),
  array('sampletypeid' => '0217','salesgroup' => 'default','sampletypeName' => 'Compressed air','SalesPrice' => '0','StandardCode' => 'ISO 8573-1:2010','ControlParameter' => '0'),
  array('sampletypeid' => '0218','salesgroup' => 'default','sampletypeName' => ' Milled cereals and pulses products ','SalesPrice' => '0','StandardCode' => 'KS 2271: 2011','ControlParameter' => '0'),
  array('sampletypeid' => '0220','salesgroup' => 'default','sampletypeName' => 'Carbonated (beverages) soft drinks - Specification.','SalesPrice' => '0','StandardCode' => 'KS EAS 29:2000','ControlParameter' => '0'),
  array('sampletypeid' => '0221','salesgroup' => 'default','sampletypeName' => 'Ready to drink alcoholic beverages - Specification','SalesPrice' => '0','StandardCode' => 'KS EAS 1598: 2015','ControlParameter' => '0'),
  array('sampletypeid' => '0222','salesgroup' => 'default','sampletypeName' => 'Chillies and capsicums, whole or ground ( powdered)','SalesPrice' => '0','StandardCode' => 'KS ISO 972:1997','ControlParameter' => '0'),
  array('sampletypeid' => '0223','salesgroup' => 'default','sampletypeName' => 'Specification for dehydrated garlic (Allium sativum L.)','SalesPrice' => '0','StandardCode' => 'KS ISO 5560:1998','ControlParameter' => '0'),
  array('sampletypeid' => '0224','salesgroup' => 'default','sampletypeName' => ' Fenugreek seed powder','SalesPrice' => '0','StandardCode' => 'KS 1162:2008','ControlParameter' => '0'),
  array('sampletypeid' => '0225','salesgroup' => 'default','sampletypeName' => ' Food seasoning mixtures — Specification','SalesPrice' => '0','StandardCode' => 'KS 1095:2023','ControlParameter' => '0'),
  array('sampletypeid' => '0226','salesgroup' => 'default','sampletypeName' => 'KS EAS 27:2023 UHT Milk specifications','SalesPrice' => '0','StandardCode' => 'KS EAS 27:2023','ControlParameter' => '0')
);

 foreach ($sampletypes as $row) {
    
 $code =$row['sampletypeid'];
 $name =$row['sampletypeName'] ;       
 $description="Unless otherwise stated, the results shown in the report refer only to the sample(s) received.
 KS - Kenyan Standard.
 EAS - East African Standard.
 X2- No standard limits provided for this parameter
 ISO- International organization for standardization
 EPA- Environmental protection agency method 5035
 LWTP- Lab works test procedure
 AOAC- Association of Official Analytical Chemists";
 $regulation="";
  $createdAt = date('Y-m-d H:i:s');
  
 $sql = "INSERT INTO TestStandards (StandardCode, StandardName, Description, ApplicableRegulation, CreatedAt)  VALUES (?, ?, ?, ?, ?)";
 $stmt = $conn->prepare($sql);
            if ($stmt) {
                // Bind parameters (s = string, i = integer, d = double, b = blob)
                $stmt->bind_param("sssss", $code, $name, $description, $regulation, $createdAt);
                 // Execute the statement
                if ($stmt->execute()) {
                    $insertCount++;
                } else {
                    echo json_encode([
                        'success' => false,
                        'message' => "Error executing query: " . $stmt->error
                    ]);
                }
               // Close the statement
                $stmt->close();
            } else {
               echo json_encode([
                        'success' => false,
                        'message' => "Error preparing query: " . $conn->error
                    ]);
            }
 }       
/* `version2lims`.`sampletypes` */